package po;
// Generated 2013-12-21 21:53:49 by Hibernate Tools 3.6.0



/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private int authorNo;
     private String authorId;
     private String paperId;
     private String authorName;
     private String organization;
     private String post;
     private char selfSchool;
     private char correspond;
     private int ranking;

    public Author() {
    }

    public Author(int authorNo, String authorId, String paperId, String authorName, String organization, String post, char selfSchool, char correspond, int ranking) {
       this.authorNo = authorNo;
       this.authorId = authorId;
       this.paperId = paperId;
       this.authorName = authorName;
       this.organization = organization;
       this.post = post;
       this.selfSchool = selfSchool;
       this.correspond = correspond;
       this.ranking = ranking;
    }
   
    public int getAuthorNo() {
        return this.authorNo;
    }
    
    public void setAuthorNo(int authorNo) {
        this.authorNo = authorNo;
    }
    public String getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }
    public String getPaperId() {
        return this.paperId;
    }
    
    public void setPaperId(String paperId) {
        this.paperId = paperId;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }
    public char getSelfSchool() {
        return this.selfSchool;
    }
    
    public void setSelfSchool(char selfSchool) {
        this.selfSchool = selfSchool;
    }
    public char getCorrespond() {
        return this.correspond;
    }
    
    public void setCorrespond(char correspond) {
        this.correspond = correspond;
    }
    public int getRanking() {
        return this.ranking;
    }
    
    public void setRanking(int ranking) {
        this.ranking = ranking;
    }




}


