package po;
// Generated 2013-12-21 21:53:49 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Degrees generated by hbm2java
 */
public class Degrees  implements java.io.Serializable {


     private int degreeNo;
     private String teacherId;
     private String degree;
     private String eduBack;
     private String school;
     private String major;
     private Date startTime;
     private Date overTime;
     private String schoolLevel;
     private char dhighest;
     private char ehighest;

    public Degrees() {
    }

    public Degrees(int degreeNo, String teacherId, String degree, String eduBack, String school, String major, Date startTime, Date overTime, String schoolLevel, char dhighest, char ehighest) {
       this.degreeNo = degreeNo;
       this.teacherId = teacherId;
       this.degree = degree;
       this.eduBack = eduBack;
       this.school = school;
       this.major = major;
       this.startTime = startTime;
       this.overTime = overTime;
       this.schoolLevel = schoolLevel;
       this.dhighest = dhighest;
       this.ehighest = ehighest;
    }
   
    public int getDegreeNo() {
        return this.degreeNo;
    }
    
    public void setDegreeNo(int degreeNo) {
        this.degreeNo = degreeNo;
    }
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }
    public String getEduBack() {
        return this.eduBack;
    }
    
    public void setEduBack(String eduBack) {
        this.eduBack = eduBack;
    }
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getOverTime() {
        return this.overTime;
    }
    
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }
    public String getSchoolLevel() {
        return this.schoolLevel;
    }
    
    public void setSchoolLevel(String schoolLevel) {
        this.schoolLevel = schoolLevel;
    }
    public char getDhighest() {
        return this.dhighest;
    }
    
    public void setDhighest(char dhighest) {
        this.dhighest = dhighest;
    }
    public char getEhighest() {
        return this.ehighest;
    }
    
    public void setEhighest(char ehighest) {
        this.ehighest = ehighest;
    }




}


