package po;
// Generated 2013-12-21 21:53:49 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Honor generated by hbm2java
 */
public class Honor  implements java.io.Serializable {


     private int honorNo;
     private String teacherId;
     private String name;
     private Date gotTime;
     private int batch;
     private String level;

    public Honor() {
    }

    public Honor(int honorNo, String teacherId, String name, Date gotTime, int batch, String level) {
       this.honorNo = honorNo;
       this.teacherId = teacherId;
       this.name = name;
       this.gotTime = gotTime;
       this.batch = batch;
       this.level = level;
    }
   
    public int getHonorNo() {
        return this.honorNo;
    }
    
    public void setHonorNo(int honorNo) {
        this.honorNo = honorNo;
    }
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getGotTime() {
        return this.gotTime;
    }
    
    public void setGotTime(Date gotTime) {
        this.gotTime = gotTime;
    }
    public int getBatch() {
        return this.batch;
    }
    
    public void setBatch(int batch) {
        this.batch = batch;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }




}


