package po;
// Generated 2013-12-21 21:53:49 by Hibernate Tools 3.6.0



/**
 * Manager generated by hbm2java
 */
public class Manager  implements java.io.Serializable {


     private String managerId;
     private String name;
     private String college;
     private String password;
     private String isSuper;

    public Manager() {
    }

    public Manager(String managerId, String name, String college, String password, String isSuper) {
       this.managerId = managerId;
       this.name = name;
       this.college = college;
       this.password = password;
       this.isSuper = isSuper;
    }
   
    public String getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getIsSuper() {
        return this.isSuper;
    }
    
    public void setIsSuper(String isSuper) {
        this.isSuper = isSuper;
    }




}


