package po;
// Generated 2013-12-21 21:53:49 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Parttimejob generated by hbm2java
 */
public class Parttimejob  implements java.io.Serializable {


     private int jobNo;
     private String teacherId;
     private String name;
     private Date startTime;
     private Date overTime;

    public Parttimejob() {
    }

    public Parttimejob(int jobNo, String teacherId, String name, Date startTime, Date overTime) {
       this.jobNo = jobNo;
       this.teacherId = teacherId;
       this.name = name;
       this.startTime = startTime;
       this.overTime = overTime;
    }
   
    public int getJobNo() {
        return this.jobNo;
    }
    
    public void setJobNo(int jobNo) {
        this.jobNo = jobNo;
    }
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getOverTime() {
        return this.overTime;
    }
    
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }




}


