package po;
// Generated 2013-12-21 21:53:49 by Hibernate Tools 3.6.0



/**
 * Reward generated by hbm2java
 */
public class Reward  implements java.io.Serializable {


     private int rewardNo;
     private String paperId;
     private String teacherId;
     private String keepSite;

    public Reward() {
    }

    public Reward(int rewardNo, String paperId, String teacherId, String keepSite) {
       this.rewardNo = rewardNo;
       this.paperId = paperId;
       this.teacherId = teacherId;
       this.keepSite = keepSite;
    }
   
    public int getRewardNo() {
        return this.rewardNo;
    }
    
    public void setRewardNo(int rewardNo) {
        this.rewardNo = rewardNo;
    }
    public String getPaperId() {
        return this.paperId;
    }
    
    public void setPaperId(String paperId) {
        this.paperId = paperId;
    }
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }
    public String getKeepSite() {
        return this.keepSite;
    }
    
    public void setKeepSite(String keepSite) {
        this.keepSite = keepSite;
    }




}


