package po;
// Generated 2013-12-21 21:53:49 by Hibernate Tools 3.6.0



/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private String subjectId;
     private String subjectName;
     private String rank;
     private String level;

    public Subject() {
    }

    public Subject(String subjectId, String subjectName, String rank, String level) {
       this.subjectId = subjectId;
       this.subjectName = subjectName;
       this.rank = rank;
       this.level = level;
    }
   
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public String getRank() {
        return this.rank;
    }
    
    public void setRank(String rank) {
        this.rank = rank;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }




}


