package po;
// Generated 2013-12-21 21:53:49 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private String teacherId;
     private Date birthdate;
     private String polity;
     private String hometown;
     private String nation;
     private String identity;
     private String post;
     private String techPost;
     private String workAddress;
     private String telephone;
     private String firstMail;
     private String secondMail;
     private String thirdMail;
     private String mobile;
     private String mailAddress;
     private String direction;
     private String tutorType;
     private String postcode;
     private String teacherImg ="000";

    public Teacher() {
    }

	
    public Teacher(String teacherId, Date birthdate, String polity, String hometown, String nation, String identity, String firstMail, String direction, String postcode) {
        this.teacherId = teacherId;
        this.birthdate = birthdate;
        this.polity = polity;
        this.hometown = hometown;
        this.nation = nation;
        this.identity = identity;
        this.firstMail = firstMail;
        this.direction = direction;
        this.postcode = postcode;
    }
    public Teacher(String teacherId, Date birthdate, String polity, String hometown, String nation, String identity, String post, String techPost, String workAddress, String telephone, String firstMail, String secondMail, String thirdMail, String mobile, String mailAddress, String direction, String tutorType, String postcode,String teacherImg) {
       this.teacherId = teacherId;
       this.birthdate = birthdate;
       this.polity = polity;
       this.hometown = hometown;
       this.nation = nation;
       this.identity = identity;
       this.post = post;
       this.techPost = techPost;
       this.workAddress = workAddress;
       this.telephone = telephone;
       this.firstMail = firstMail;
       this.secondMail = secondMail;
       this.thirdMail = thirdMail;
       this.mobile = mobile;
       this.mailAddress = mailAddress;
       this.direction = direction;
       this.tutorType = tutorType;
       this.postcode = postcode;
       this.teacherImg = teacherImg;
    }
   
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getPolity() {
        return this.polity;
    }
    
    public void setPolity(String polity) {
        this.polity = polity;
    }
    public String getHometown() {
        return this.hometown;
    }
    
    public void setHometown(String hometown) {
        this.hometown = hometown;
    }
    public String getNation() {
        return this.nation;
    }
    
    public void setNation(String nation) {
        this.nation = nation;
    }
    public String getIdentity() {
        return this.identity;
    }
    
    public void setIdentity(String identity) {
        this.identity = identity;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }
    public String getTechPost() {
        return this.techPost;
    }
    
    public void setTechPost(String techPost) {
        this.techPost = techPost;
    }
    public String getWorkAddress() {
        return this.workAddress;
    }
    
    public void setWorkAddress(String workAddress) {
        this.workAddress = workAddress;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getFirstMail() {
        return this.firstMail;
    }
    
    public void setFirstMail(String firstMail) {
        this.firstMail = firstMail;
    }
    public String getSecondMail() {
        return this.secondMail;
    }
    
    public void setSecondMail(String secondMail) {
        this.secondMail = secondMail;
    }
    public String getThirdMail() {
        return this.thirdMail;
    }
    
    public void setThirdMail(String thirdMail) {
        this.thirdMail = thirdMail;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getMailAddress() {
        return this.mailAddress;
    }
    
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }
    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }
    public String getTutorType() {
        return this.tutorType;
    }
    
    public void setTutorType(String tutorType) {
        this.tutorType = tutorType;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getTeacherImg() {
        return teacherImg;
    }

    public void setTeacherImg(String teacherImg) {
        this.teacherImg = teacherImg;
    }




}


