package po;
// Generated 2013-12-21 21:53:49 by Hibernate Tools 3.6.0



/**
 * Tsbelong generated by hbm2java
 */
public class Tsbelong  implements java.io.Serializable {


     private String teacherId;
     private String mainFirst;
     private String mainSecOne;
     private String mainSecTwo;
     private String nextFirst;
     private String nextSecOne;
     private String nextSecTwo;

    public Tsbelong() {
    }

	
    public Tsbelong(String teacherId, String mainFirst, String mainSecOne) {
        this.teacherId = teacherId;
        this.mainFirst = mainFirst;
        this.mainSecOne = mainSecOne;
    }
    public Tsbelong(String teacherId, String mainFirst, String mainSecOne, String mainSecTwo, String nextFirst, String nextSecOne, String nextSecTwo) {
       this.teacherId = teacherId;
       this.mainFirst = mainFirst;
       this.mainSecOne = mainSecOne;
       this.mainSecTwo = mainSecTwo;
       this.nextFirst = nextFirst;
       this.nextSecOne = nextSecOne;
       this.nextSecTwo = nextSecTwo;
    }
   
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }
    public String getMainFirst() {
        return this.mainFirst;
    }
    
    public void setMainFirst(String mainFirst) {
        this.mainFirst = mainFirst;
    }
    public String getMainSecOne() {
        return this.mainSecOne;
    }
    
    public void setMainSecOne(String mainSecOne) {
        this.mainSecOne = mainSecOne;
    }
    public String getMainSecTwo() {
        return this.mainSecTwo;
    }
    
    public void setMainSecTwo(String mainSecTwo) {
        this.mainSecTwo = mainSecTwo;
    }
    public String getNextFirst() {
        return this.nextFirst;
    }
    
    public void setNextFirst(String nextFirst) {
        this.nextFirst = nextFirst;
    }
    public String getNextSecOne() {
        return this.nextSecOne;
    }
    
    public void setNextSecOne(String nextSecOne) {
        this.nextSecOne = nextSecOne;
    }
    public String getNextSecTwo() {
        return this.nextSecTwo;
    }
    
    public void setNextSecTwo(String nextSecTwo) {
        this.nextSecTwo = nextSecTwo;
    }




}


