package po;
// Generated 2013-12-21 21:53:49 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Workexprience generated by hbm2java
 */
public class Workexprience  implements java.io.Serializable {


     private int workNo;
     private String teacherId;
     private Date startTime;
     private Date overTime;
     private String orginization;
     private String department;
     private String post;

    public Workexprience() {
    }

    public Workexprience(int workNo, String teacherId, Date startTime, Date overTime, String orginization, String department, String post) {
       this.workNo = workNo;
       this.teacherId = teacherId;
       this.startTime = startTime;
       this.overTime = overTime;
       this.orginization = orginization;
       this.department = department;
       this.post = post;
    }
   
    public int getWorkNo() {
        return this.workNo;
    }
    
    public void setWorkNo(int workNo) {
        this.workNo = workNo;
    }
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getOverTime() {
        return this.overTime;
    }
    
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }
    public String getOrginization() {
        return this.orginization;
    }
    
    public void setOrginization(String orginization) {
        this.orginization = orginization;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }




}


